Feature/initial debianize
wirenboard/wb-cc2652p-flasher pull request #2
Opened 2023-01-26 13:48 UTC by lostpoint-ru

2023-01-27 07:45 UTC, webconn requested changes
Слишком сильно влез в сторонние файлы, это будет вызывать проблемы с мержами из апстрима. Вряд ли мы будем сильно менять эти скрипты.

Предлагаю переименованные файлы вернуть обратно, в родной readme добавить просто в начало строчку со ссылкой на `README.wb.md` (где будет наш readme).

И pybuild тут явно не нужен

2023-01-27 07:45 UTC, webconn commented on cc2538-bsl.py
> +import binascii
А какие-то наши **значительные** изменения в этот файл заезжали? Если нет, то сейчас приведение к нашим форматам вызовет больше проблем, потому что мы никогда не сможем смержить это с апстримом.

2023-01-27 07:45 UTC, webconn commented on debian/rules
> +export PYBUILD_NAME=wb-cc2652p-flasher
Так разве нам нужен `pybuild` здесь, если мы всего лишь хотели один скрипт положить в `/usr/bin`?

2023-01-27 10:14 UTC, lostpoint-ru commented on cc2538-bsl.py
> +import binascii
откатил линтинг

2023-01-27 10:14 UTC, lostpoint-ru commented on debian/rules
> +export PYBUILD_NAME=wb-cc2652p-flasher
ликвидировал pybuild

2023-01-27 12:16 UTC, vdromanov commented on wb-cc2652p-flasher
> +if [ ! -e "/sys/class/gpio/gpio$RTS_GPIO" ]
а почему в одной тулзе сразу sysfs и libgpiod?
давай и gpio дергать через gpiod

![2023-01-27_15-15-53](https://user-images.githubusercontent.com/25829054/215085016-d0dbcdcc-699c-49c8-9e98-fdbb803c9b4b.png)

2023-01-27 12:17 UTC, vdromanov commented on wb-cc2652p-flasher
> +then
и расписать комментами бы, зачем мы гпиом дергаем

2023-01-27 12:19 UTC, vdromanov commented on wb-cc2652p-flasher
> +
давай set -e в начало

2023-01-27 12:20 UTC, vdromanov commented on README.md
> +(Additional Wiren Board `wb-cc2652p-flashed` command README see [here](README.wb.md))
отсутствие запуска тестов меня, конечно, смущает (хоть тесты и такие себе)

=> если запускать их не будешь - хоть здесь напиши, что пакетик собираем без запуска тестов

2023-01-27 12:22 UTC, vdromanov commented on README.wb.md
> +Note: you need to stop zigbee2mqtt before updating module firmware
а мб zigbee2mqtt на паузу ставить в процессе обновления?
тип как в упдатере сделано с сериалом

killall -STOP зигби
killall -CONT зигби

2023-01-27 12:24 UTC, vdromanov commented on README.wb.md
> +Note: you need to stop zigbee2mqtt before updating module firmware
здесь не настаиваю; башем неудобно try/finally делать

2023-01-27 17:58 UTC, webconn commented on README.md
> +(Additional Wiren Board `wb-cc2652p-flashed` command README see [here](README.wb.md))
Это ж не наш софт, мы скрипт взяли без изменений чужой

2023-01-27 18:00 UTC, webconn approved these changes
По моим замечаниям вопросов нет больше

2023-01-30 08:30 UTC, lostpoint-ru commented on wb-cc2652p-flasher
> +if [ ! -e "/sys/class/gpio/gpio$RTS_GPIO" ]
> а почему в одной тулзе сразу sysfs и libgpiod? давай и gpio дергать через gpiod

Пробовал, через gpioset  почему-то сходу не заработало, решил не закапываться в это и оставить существующее работающее решение. 

Это критично?

2023-01-30 08:35 UTC, lostpoint-ru commented on wb-cc2652p-flasher
> +then
добавил

2023-01-30 08:35 UTC, lostpoint-ru commented on wb-cc2652p-flasher
> +
добавил

2023-01-30 09:18 UTC, lostpoint-ru commented on README.wb.md
> +Note: you need to stop zigbee2mqtt before updating module firmware
killall тут не подходит, т.к. рабочий процесс светится как node index.js, а возиться с systemctl это прям оверкилл, особенно с учетом set -e

Предлагаю забить.

2023-01-30 10:50 UTC, vdromanov commented on wb-cc2652p-flasher
> +if [ ! -e "/sys/class/gpio/gpio$RTS_GPIO" ]
ну это - не очень хорошо, т.к. наш другой софт может в этот gpio сходить => увидеть, что он экспортирован => неизвестно, что произойдёт

нас частично set -e спасает, т.к. прошивалка упадёт, если gpio занят

=> попробуй еще разок, как у меня на картинке; не получится - забиваем

2023-01-30 10:50 UTC, vdromanov approved these changes

2023-01-30 11:58 UTC, vdromanov approved these changes

2023-01-30 12:00 UTC, merged